services:
  postgres:
    image: postgres:16-alpine
    container_name: e7d-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: e7d
      POSTGRES_PASSWORD: e7d
      POSTGRES_DB: e7ddb
    ports:
      - '5432:5432'
    volumes:
      - e7d_pgdata:/var/lib/postgresql/data

volumes:
  e7d_pgdata:
